### PR TITLE
added CUnit support

### PR DESCRIPTION
**Pull request by zcsahok**
and some tests for locator2longlat.c
further tests (also for other C files) can be added using the same format, they will be used automatically.

### CODE REVIEW

**Comment by dl1jbe** [comment]
Thanks for the good start with CUnit. I already did some testing work with CMocka in an unpublished branch. Maybe we can integrate that also
There is also a way to change the base Makefile.am so that tests will be supprted with a simple 'make check'.

But atm I am lying in bed with quite some fever. So do not expect a lot of help for now.

**Comment by dl1jbe** [comment]
Something is wrong. The merge landed in your repo,weird??? I just merged and closed the pull request. Please do a second check.

**Comment by zcsahok** [comment]
Indeed, it's in my repo:
commit f46708db296c387de0e4f87c524d6a27e20bd042
>  Merge branch 'master' into master
> dl1jbe committed 39 minutes ago

There are no changed files, at least that's ok.
Strange.

**Comment by dl1jbe** [comment]
Can you please try a second pull request?

**Comment by zcsahok** [comment]
The link in prev comment points to your repo, here is the "same" commit in my repo. It has the same id.

https://github.com/zcsahok/test-travis/commit/f46708db296c387de0e4f87c524d6a27e20bd042

**Comment by zcsahok** [comment]
ok

**Comment by dl1jbe** [comment]
The weird thing is, the first merge is not visible in my repo.

In meantime the check are done, I try to merge the second one....

**Comment by dl1jbe** [comment]
Hmm the button says 'merge' but if I do it the message is 'dl1jbe closed it'. No idea...

**Pull request closed without merging**
